version: "3"

services:
  api:
    container_name: cotabox-api
    restart: always
    build: .
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - "4000:4000"
    expose:
      - "4000"
    #command: "yarn serve"
    environment:
      WAIT_HOSTS: mongodb:27017
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"